DO NOT SIMPLY MERGE READ DESCRIPTION - InstallUtil doesn't work with net10? net core? service executables
We tried installing a service executable converted from .net framework 4.8 to net10 using installUtil, as suggested here, but that errored because of a BadImageFormatException:

> Beim Initialisieren der Installation ist eine Ausnahme aufgetreten:
System.BadImageFormatException: Die Datei oder Assembly "file:///D:\Publish\NexusCbfcLite\Nexus.BackgroundService.exe" oder eine Abhängigkeit davon wurde nicht gefunden. Im Modul wurde ein Assemblymanifest erwartet.

i kinda expected that since ServiceUtil is a .net framework process.

using `sc create` worked, though. documentation shoud reflect this (after this is cleared to be correct, of course)